main: community.leaf.survival.staffmode.StaffModePlugin
name: Survival-Staff-Mode
version: ${project.version}
api-version: 1.13

author: RezzedUp
description: ${project.description}
website: ${project.url}

softdepend: [Vault, dynmap]

commands:
  staffmode:
    aliases: [staff-mode, smode, sm, smh]
    description: Toggle staff mode.
    permission: survival-staff-mode.staff

permissions:
  survival-staff-mode.staff:
    description: Toggle staff mode for yourself.
    default: op
  survival-staff-mode.enabled:
    description: |
      Signifies that staff mode is enabled.
      Only add this permission to a rank that's assigned when players enter staff mode.
    default: false
    children:
      survival-staff-mode.staff: true
  survival-staff-mode.admin:
    description: Manage the SurvivalStaffMode plugin (reload configs, etc).
    default: op
    children:
      survival-staff-mode.staff: true
