main: community.leaf.survival.staffmode.StaffModePlugin
name: ${project.name}
version: ${project.version}
api-version: 1.13

author: RezzedUp
description: ${project.description}

commands:
  test-snapshots:
    permission: survivalstaffmode.debug
